version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "2.7"
  apt_packages:  # needed for dbus-python package
    - build-essential
    - libpython2-dev
    - libdbus-1-dev

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

sphinx:
  fail_on_warning: true

